### ISSUE TITLE
Is the protobuf2LefDef script available?

### ISSUE THREAD

**Issue by ZhuLinsen** [RustamC/circuit_training_openlane#1]
Hello @RustamC, I found what you have done really helpful for me, and I have several questions I would like to ask:

1、Is the protobuf2LefDef script available? I noticed the information in the README.md file:
`p2d - converts ProtoBuf into LEF/DEF (actually, just updates coordinates in the original DEF). WARNING: Doesn't work at this moment.`

2、I attempted to integrate DREAMPlace into the OpenROAD-flow-scripts. I ran it with routability_opt_flag and timing_opt_flag disabled. However, the output solution cannot be routed in the next steps. Furthermore, it failed when I enabled routability_opt_flag and timing_opt_flag. Do you have any suggestions regarding this issue?

3、As a beginner in chip placement and AI4EDA, I would greatly appreciate any advice or guidance you could provide on how to rapidly progress in this field.

I apologize for being a bit verbose, but I truly value your advice and assistance. I am sincerely grateful for your help. Thank you very much.

Best regards,
linsen

**Comment by RustamC** [comment]
Hi, @ZhuLinsen ! You're welcome!
1. Just in case, in `p2d` mode, script doesn't create a new DEF file from scratch, it just updates coordinates in the original DEF file. That's why, I don't recommend using this option. As for the class that performs conversion it can be found here: https://github.com/RustamC/circuit_training/blob/80fe78fc795d9390048aa795ce6feb3edf2f6706/circuit_training/convertor/convertor.py#L1001
2. Try to decrease `target_density` parameter. It should free up more space for routing.
3. I would recommend starting with the review articles (for example, [Progress of Placement Optimization for Accelerating VLSI Physical Design](https://www.mdpi.com/2079-9292/12/2/337), [ML for EDA](https://vlsicad.ucsd.edu/Publications/Journals/j138.pdf)) in these areas and then look at the specific papers ([DREAMPlace](https://github.com/limbo018/DREAMPlace#publications), [AutoDMP](https://research.nvidia.com/publication/2023-03_autodmp-automated-dreamplace-based-macro-placement)) for more details.

**Comment by ZhuLinsen** [comment]
Thank you very much，@RustamC .I will try your advice soon. Thank you again!
